<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Symfony\\Component\\Routing\\' => $vendorDir . '/symfony/routing',
    'Symfony\\Component\\HttpFoundation\\' => $vendorDir . '/symfony/http-foundation',
    'Symfony\\Component\\EventDispatcher\\' => $vendorDir . '/symfony/event-dispatcher',
    'React\\Stream' => $vendorDir . '/react/stream',
    'React\\Socket' => $vendorDir . '/react/socket',
    'React\\EventLoop' => $vendorDir . '/react/event-loop',
    'Ratchet' => $vendorDir . '/cboden/ratchet/src',
    'Guzzle\\Stream' => $vendorDir . '/guzzle/stream',
    'Guzzle\\Parser' => $vendorDir . '/guzzle/parser',
    'Guzzle\\Http' => $vendorDir . '/guzzle/http',
    'Guzzle\\Common' => $vendorDir . '/guzzle/common',
    'Evenement' => $vendorDir . '/evenement/evenement/src',
);
